import turtle
import time
s=turtle.Screen()
s.title("ONE MINUTE TIMER")
s.bgcolor("red")
t=turtle.Turtle()
t.color("black")
t.pensize(5)
t.hideturtle()
tr=turtle.Turtle()
tr.color("black")
tr.up()
tr.goto(-15,-20)
tr.hideturtle()
t.up()
t.goto(0,-100)
t.down()
t.speed(0)
for i in range(60):
    tr.reset()
    tr.hideturtle()
    tr.up()
    tr.goto(-15,-20)
    t.circle(100,6)
    tr.write(60-i,font=("calibari",20))
    time.sleep(1)
t.up()
t.goto(-65,200)
t.write("TIME UP",font=("calibari",20))
